package com.fruizc.sites.modeldb;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fruizc.sites.modeldb.User;
import com.fruizc.sites.modeldb.Place;
import com.fruizc.sites.modeldb.PlaceUser;

import com.fruizc.sites.modeldb.UserDao;
import com.fruizc.sites.modeldb.PlaceDao;
import com.fruizc.sites.modeldb.PlaceUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig placeDaoConfig;
    private final DaoConfig placeUserDaoConfig;

    private final UserDao userDao;
    private final PlaceDao placeDao;
    private final PlaceUserDao placeUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        placeDaoConfig = daoConfigMap.get(PlaceDao.class).clone();
        placeDaoConfig.initIdentityScope(type);

        placeUserDaoConfig = daoConfigMap.get(PlaceUserDao.class).clone();
        placeUserDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        placeDao = new PlaceDao(placeDaoConfig, this);
        placeUserDao = new PlaceUserDao(placeUserDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Place.class, placeDao);
        registerDao(PlaceUser.class, placeUserDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        placeDaoConfig.clearIdentityScope();
        placeUserDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PlaceDao getPlaceDao() {
        return placeDao;
    }

    public PlaceUserDao getPlaceUserDao() {
        return placeUserDao;
    }

}
