package com.fruizc.sites.modeldb;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PLACE_USER".
 */
@Entity
public class PlaceUser {
    private Long idPlace;
    private String useremail;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public PlaceUser() {
    }

    @Generated
    public PlaceUser(Long idPlace, String useremail) {
        this.idPlace = idPlace;
        this.useremail = useremail;
    }

    public Long getIdPlace() {
        return idPlace;
    }

    public void setIdPlace(Long idPlace) {
        this.idPlace = idPlace;
    }

    public String getUseremail() {
        return useremail;
    }

    public void setUseremail(String useremail) {
        this.useremail = useremail;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
